# render.yaml (na RAIZ do repositório)
services:
  - type: web
    name: orbent-api
    env: python
    plan: free
    rootDirectory: plano/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173
